name: "Docs / Tier-1 task"
description: "코드 변경 없이 기여 가능한 태스크"
labels: ["Level 1: Welcome!", "docs", "good first issue"]

body:
  - type: textarea
    id: summary
    attributes:
      label: 작업 내용
      description: 이슈 목적과 변경 포인트를 bullet로 작성
    validations:
      required: true

  - type: textarea
    id: dod
    attributes:
      label: 수락 기준(Definition of Done)
      description: 체크리스트 형태로 적어주세요
    validations:
      required: true

  - type: checkboxes
    id: submit
    attributes:
      label: 제출 안내
      options:
        - label: PR에 변경 전/후 스크린샷 첨부
        - label: 출처 표기
